name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        source-url: https://devops.see.asseco.com/Digital/_packaging/Asseco/nuget/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.ASSECONUGET }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack   
      run: dotnet pack -c Release -p:PackageVersion=$(cat .version)
    - name: Publish Nuget
      run: dotnet nuget push **/*.nupkg
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.ASSECONUGET }}
  